// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isIosRuntime(): boolean {
  if (typeof window === 'undefined' || typeof navigator === 'undefined') return false;
  const cap = (window as any).Capacitor;
  return (
    /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    (navigator.platform === 'MacIntel' && (navigator as any).maxTouchPoints > 1) ||
    window.location.protocol === 'capacitor:' ||
    cap?.getPlatform?.() === 'ios' ||
    !!cap?.isNativePlatform?.() ||
    !!(window as any).webkit?.messageHandlers?.bridge
  );
}

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

const originalSignInWithOAuth = supabase.auth.signInWithOAuth.bind(supabase.auth);

supabase.auth.signInWithOAuth = ((credentials: any) => {
  if (credentials?.provider === 'google' && isIosRuntime()) {
    console.error('[supabase] Blocked Google web OAuth on iOS runtime');
    return Promise.resolve({
      data: { provider: 'google', url: null },
      error: new Error('Google web OAuth is blocked on iOS because it opens Safari. Use native Google sign-in.'),
    } as any);
  }

  return originalSignInWithOAuth(credentials);
}) as typeof supabase.auth.signInWithOAuth;